[package]
name = "sylvia"
version = { workspace = true }
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2021"
description = "Framework for generating trait based CosmWasm smart contracts"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/sylvia"
homepage = "https://cosmwasm.com"
keywords = ["cosmwasm", "blockchain", "confio"]
categories = ["api-bindings", "wasm"]

[features]
mt = [
    "sylvia-derive/mt",
    "dep:cw-multi-test",
    "dep:anyhow",
    "dep:derivative",
    "cosmwasm-std/cosmwasm_1_2",
    "dep:cw-utils",
]
stargate = ["cosmwasm-std/stargate", "cw-multi-test?/stargate"]
staking = ["cosmwasm-std/staking", "cw-multi-test?/staking"]

[dependencies]
sylvia-derive = { workspace = true }
cosmwasm-std = { version = "1.5", features = ["staking"] }
cosmwasm-schema = "1.5"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-cw-value = "0.7.0"
serde-json-wasm = "1.0.0"
konst = "0.3"
cw-multi-test = { version = "0.18.0", optional = true, features = [
    "cosmwasm_1_2",
] }
anyhow = { version = "1.0", optional = true }
derivative = { version = "2.2.0", optional = true }
cw-utils = { version = "1.0.2", optional = true }

[dev-dependencies]
anyhow = "1.0"
cosmwasm-std = { version = "1.5", features = ["staking", "cosmwasm_1_2"] }
cw-multi-test = "0.18"
cw-storage-plus = "1.2.0"
cw-utils = "1.0.2"
thiserror = "1.0.50"
