[package]
name = "sylvia"
version = "0.3.0"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2021"
description = "Framework for generating trait based CosmWasm smart contracts"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/sylvia"
homepage = "https://cosmwasm.com"
keywords = ["cosmwasm", "blockchain", "confio"]
categories = ["api-bindings", "wasm"]

[features]
mt = ["sylvia-derive/mt", "dep:cw-multi-test"]

[dependencies]
sylvia-derive = { version = "0.3.0", path = "../sylvia-derive" }
cosmwasm-std = { version = "1.2", features = ["staking"] }
cosmwasm-schema = "1.2"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-cw-value = "0.7.0"
konst = "0.3"
cw-multi-test = { version = "0.16.2", optional = true }

[dev-dependencies]
anyhow = "1.0"
cw-storage-plus = "1.0.1"
cw-multi-test = "0.16.2"
thiserror = "1.0.38"
