[package]
name = "sylvia"
version = "0.1.1"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2021"
description = "Framework for generating trait based CosmWasm smart contracts"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/sylvia"
homepage = "https://cosmwasm.com"
keywords = ["cosmwasm", "blockchain", "confio"]
categories = ["api-bindings", "wasm"]


[dependencies]
sylvia-derive = { path = "../sylvia-derive" }
cosmwasm-std = { version = "1", features = ["staking"] }
schemars = "0.8.10"
serde = { version = "1", default-features = false, features = ["derive"] }
serde-cw-value = { version = "0.7.0", git = "https://github.com/hashedone/serde-cw-value.git" }
