[workspace]
members = [
  "sylvia",
  "sylvia-derive",

]
exclude = ["examples/*"]
resolver = "2"

[workspace.package]
version = "0.5.0"

[workspace.dependencies]
sylvia-derive = { version = "0.5.0", path = "sylvia-derive" }
