[workspace]
members = [
  "sylvia",
  "sylvia-derive",

  # Contract intefaces
  "interfaces/cw1",
  "interfaces/cw4",
  "interfaces/cw20-allowances",
  "interfaces/cw20-minting",
  "interfaces/cw20-marketing",

  # Contracts
  "contracts/cw1-whitelist",
  "contracts/cw1-subkeys",
  "contracts/cw20-base",
]
resolver = "2"
