[workspace]
members = ["sylvia", "sylvia-derive"]
exclude = ["examples/*"]
resolver = "2"

[workspace.package]
version = "1.0.1"

[workspace.dependencies]
sylvia-derive = { version = "1.0.1", path = "sylvia-derive" }
anyhow = "1.0.82"
cosmwasm-schema = "2.0.2"
cosmwasm-std = "2.0.2"
cw-multi-test = "2.0.1"
cw-storage-plus = "2.0.0"
schemars = "0.8.16"
cw-utils = "2.0.0"
serde = { version = "1.0.198", default-features = false, features = ["derive"] }
thiserror = "1.0.59"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
