[workspace]
members = [
    "sylvia",
    "sylvia-derive",

# Contract intefaces
    "contracts/cw1",
    "contracts/cw4",
    "contracts/cw20-allowances",
    "contracts/cw20-minting",
    "contracts/cw20-marketing",

# Contracts
    "contracts/cw1-whitelist", 
    "contracts/cw1-subkeys",
    ]
