[workspace]
members = ["sylvia", "sylvia-derive"]
exclude = ["examples/*"]
resolver = "2"

[workspace.package]
version = "0.7.1"

[workspace.dependencies]
sylvia-derive = { version = "0.7.1", path = "sylvia-derive" }
