[workspace]
members = ["sylvia", "sylvia-derive"]
exclude = ["examples/*"]
resolver = "2"

[workspace.package]
version = "0.10.0"

[workspace.dependencies]
sylvia-derive = { version = "0.10.0", path = "sylvia-derive" }

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
