[workspace]
members = ["sylvia", "sylvia-derive"]
exclude = ["examples/*"]
resolver = "2"

[workspace.package]
version = "0.9.2"

[workspace.dependencies]
sylvia-derive = { version = "0.9.2", path = "sylvia-derive" }
