[package]
name = "sylvia-derive"
version = "0.2.0"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2021"
description = "Framework for generating trait based CosmWasm smart contracts - derives"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/sylvia"
homepage = "https://cosmwasm.com"
keywords = ["cosmwasm", "blockchain", "confio"]
categories = ["api-bindings", "wasm"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.101", features = ["parsing", "derive", "fold", "visit", "full", "extra-traits"] }
quote = "1.0.21"
proc-macro2 = "1.0.46"
convert_case = "0.6.0"
proc-macro-error = "1.0.4"
proc-macro-crate = "1.2.1"

[dev-dependencies]
runtime-macros-derive = { git = "https://github.com/CosmWasm/runtime-macros-derive.git", version = "0.6.0" }
