[package]
name = "sylvia-derive"
version = "0.1.2"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2021"
description = "Framework for generating trait based CosmWasm smart contracts - derives"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/sylvia"
homepage = "https://cosmwasm.com"
keywords = ["cosmwasm", "blockchain", "confio"]
categories = ["api-bindings", "wasm"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["parsing", "derive", "fold", "visit", "full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
convert_case = "0.5"
proc-macro-error = "1"
proc-macro-crate = "1.1"
konst = "0.2.15"
