[workspace]
members = [
    # Contract intefaces
    "interfaces/cw1",
    "interfaces/whitelist",
    "interfaces/cw4",
    "interfaces/cw20-allowances",
    "interfaces/cw20-minting",
    "interfaces/cw20-marketing",
    "interfaces/custom-and-generic",
    "interfaces/generic",

    # Contracts
    "contracts/cw1-whitelist",
    "contracts/cw1-subkeys",
    "contracts/cw20-base",
    "contracts/entry-points-overriding",
    "contracts/custom",
    "contracts/generic_contract",
    "contracts/generic_iface_on_contract",
]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.75"
cosmwasm-schema = "1.5.0"
cosmwasm-std = "1.5.0"
cw-multi-test = "0.20.0"
cw-storage-plus = "1.2.0"
cw-utils = "1.0.2"
cw2 = "1.1.2"
getrandom = "0.2.11"
semver = "1.0.20"
serde = { version = "1.0.192", default-features = false, features = ["derive"] }
thiserror = "1.0.50"
assert_matches = "1.5.0"
