name: Contract Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  test_project:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: macOS
            os: macOS-latest
          - build: Windows
            os: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66.0
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Test project
        run: cargo test --locked
      - name: Clippy project
        run: cargo clippy --all-targets -- -D warnings 
      - name: Fmt check project
        run: cargo fmt --check
      - name: Build cw20-base
        working-directory: contracts/cw20-base
        run: cargo build --release --target wasm32-unknown-unknown --locked --lib
      - name: Build cw1-subkeys
        working-directory: contracts/cw1-subkeys
        run: cargo build --release --target wasm32-unknown-unknown --locked --lib
      - name: Build cw1-whitelist
        working-directory: contracts/cw1-whitelist
        run: cargo build --release --target wasm32-unknown-unknown --locked --lib
      - name: Install cosmwasm-check
        run: cargo install cosmwasm-check --force
      - name: Check contracts
        run: find target/wasm32-unknown-unknown/release/ -type f -name "*.wasm" -exec cosmwasm-check {} \;
      - name: Cw1-whitelist schema
        working-directory: contracts/cw1-whitelist/
        run: cargo schema
      - name: Cw1-subkeys schema
        working-directory: contracts/cw1-subkeys
        run: cargo schema
      - name: Cw20-base schema
        working-directory: contracts/cw20-base
        run: cargo schema
      - name: Archive schema artifats
        uses: actions/upload-artifact@v3
        with:
          name: schema-json
          path: |
            contracts/cw1-subkeys/schema/cw1-subkeys.json
            contracts/cw1-whitelist/schema/cw1-whitelist.json
            contracts/cw20-base/schema/cw20-base.json

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name:                   Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          fail_ci_if_error:     true
